# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GwAswAudit < Formula
  desc "A set of commands to audit AWS usage to identify cost savings and security issues."
  homepage "https://goodwaygroup.github.io/gw-aws-audit/"
  version "1.15.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/GoodwayGroup/gw-aws-audit/releases/download/v1.15.1/gw-asw-audit_1.15.1_darwin_amd64.tar.gz"
    sha256 "e8cd10262c7af923896dadf39447fe731700c97a299a09c6270ea283a2295a87"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/GoodwayGroup/gw-aws-audit/releases/download/v1.15.1/gw-asw-audit_1.15.1_darwin_arm64.tar.gz"
    sha256 "a7b862faa59930d25737778b342aee05326f2f8b27182e1bc73679eedcf49f5f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/GoodwayGroup/gw-aws-audit/releases/download/v1.15.1/gw-asw-audit_1.15.1_linux_amd64.tar.gz"
    sha256 "11d09dd0ad7d5e0bf23b6c669d7a24b34fd582919d31465cbe141077427fb6c2"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/GoodwayGroup/gw-aws-audit/releases/download/v1.15.1/gw-asw-audit_1.15.1_linux_armv6.tar.gz"
    sha256 "97dea80af7ee19af7ec80c16cba579db2146edb43de7a232e6fcddfc6e74e4c2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/GoodwayGroup/gw-aws-audit/releases/download/v1.15.1/gw-asw-audit_1.15.1_linux_arm64.tar.gz"
    sha256 "d204ed7aad354277771b0019e8d5b4061931097d9b3d098dadbf44696272c018"
  end

  def install
    bin.install "gw-aws-audit"
  end

  test do
    system "#{bin}/gw-aws-audit --help"
  end
end
